// Compiled shader for PC, Mac & Linux Standalone, uncompressed size: 23.4KB

// Skipping shader variants that would not be included into build of current scene.

Shader "Hidden/CameraMotionBlur" {
Properties {
 _MainTex ("-", 2D) = "" { }
 _NoiseTex ("-", 2D) = "grey" { }
 _VelTex ("-", 2D) = "black" { }
 _NeighbourMaxTex ("-", 2D) = "black" { }
}
SubShader { 


 // Stats for Vertex shader:
 //        d3d9 : 5 math
 // Stats for Fragment shader:
 //        d3d9 : 27 math, 1 texture
 Pass {
  ZTest Always
  Cull Off
  GpuProgramID 31911
Program "vp" {
SubProgram "d3d9 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   row_major float4x4 glstate_matrix_mvp;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   glstate_matrix_mvp c0       4
//

    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xy
    dp4 o0.x, c0, v0
    dp4 o0.y, c1, v0
    dp4 o0.z, c2, v0
    dp4 o0.w, c3, v0
    mov o1.xy, v1

// approximately 5 instruction slots used
"
}
}
Program "fp" {
SubProgram "d3d9 " {
// Stats: 27 math, 1 textures
Matrix 0 [_ToPrevViewProjCombined]
Vector 4 [_MainTex_TexelSize]
Float 6 [_MaxVelocity]
Float 5 [_VelocityScale]
SetTexture 0 [_CameraDepthTexture] 2D 0
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   sampler2D _CameraDepthTexture;
//   float4 _MainTex_TexelSize;
//   float _MaxVelocity;
//   row_major float4x4 _ToPrevViewProjCombined;
//   float _VelocityScale;
//
//
// Registers:
//
//   Name                    Reg   Size
//   ----------------------- ----- ----
//   _ToPrevViewProjCombined c0       4
//   _MainTex_TexelSize      c4       1
//   _VelocityScale          c5       1
//   _MaxVelocity            c6       1
//   _CameraDepthTexture     s0       1
//

    ps_3_0
    def c7, 1, 2, -1, 0
    def c8, 0.5, 0.00999999978, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    mad r0.xy, v0, c7.y, c7.z
    add r0.z, c7.x, -v0.y
    cmp r1.y, c4.y, v0.y, r0.z
    mov r1.x, v0.x
    texld r1, r1, s0
    mov r1.z, r1.x
    mad r1.xyw, v0.xyzx, c7.yyzw, c7.zzzx
    dp4 r0.z, c3, r1
    rcp r0.z, r0.z
    dp4 r2.x, c0, r1
    dp4 r2.y, c1, r1
    mad r0.xy, r2, -r0.z, r0
    mov r0.zw, c4
    mul r0.zw, r0, c5.x
    mul r0.xy, r0, r0.zwzw
    mul r0.xy, r0, c8.x
    dp2add r0.z, r0, r0, c7.w
    rsq r0.z, r0.z
    rcp r0.z, r0.z
    min r1.x, c6.x, r0.z
    add r0.z, r0.z, c8.y
    rcp r0.z, r0.z
    max r0.w, c8.x, r1.x
    mul r0.xy, r0.w, r0
    mul r0.xy, r0.z, r0
    mul oC0.xy, r0, c4
    mov oC0.zw, c7.w

// approximately 28 instruction slots used (1 texture, 27 arithmetic)
"
}
}
 }


 // Stats for Vertex shader:
 //        d3d9 : 5 math
 // Stats for Fragment shader:
 //        d3d9 : 3 math, 1 texture
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 74517
Program "vp" {
SubProgram "d3d9 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   row_major float4x4 glstate_matrix_mvp;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   glstate_matrix_mvp c0       4
//

    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xy
    dp4 o0.x, c0, v0
    dp4 o0.y, c1, v0
    dp4 o0.z, c2, v0
    dp4 o0.w, c3, v0
    mov o1.xy, v1

// approximately 5 instruction slots used
"
}
}
Program "fp" {
SubProgram "d3d9 " {
// Stats: 3 math, 1 textures
Float 0 [_DisplayVelocityScale]
SetTexture 0 [_MainTex] 2D 0
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   float _DisplayVelocityScale;
//   sampler2D _MainTex;
//
//
// Registers:
//
//   Name                  Reg   Size
//   --------------------- ----- ----
//   _DisplayVelocityScale c0       1
//   _MainTex              s0       1
//

    ps_3_0
    def c1, 1, -1, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    texld r0, v0, s0
    abs r1.y, r0.y
    mul r1.xzw, r0.xyxy, c1.xyyy
    mul_sat oC0, r1, c0.x

// approximately 4 instruction slots used (1 texture, 3 arithmetic)
"
}
}
 }


 // Stats for Vertex shader:
 //        d3d9 : 5 math
 // Stats for Fragment shader:
 //        d3d9 : 26 math, 2 texture, 10 branch
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 147757
Program "vp" {
SubProgram "d3d9 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   row_major float4x4 glstate_matrix_mvp;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   glstate_matrix_mvp c0       4
//

    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xy
    dp4 o0.x, c0, v0
    dp4 o0.y, c1, v0
    dp4 o0.z, c2, v0
    dp4 o0.w, c3, v0
    mov o1.xy, v1

// approximately 5 instruction slots used
"
}
}
Program "fp" {
SubProgram "d3d9 " {
// Stats: 26 math, 2 textures, 10 branches
Vector 1 [_MainTex_TexelSize]
Float 0 [_MaxRadiusOrKInPaper]
SetTexture 0 [_MainTex] 2D 0
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   sampler2D _MainTex;
//   float4 _MainTex_TexelSize;
//   float _MaxRadiusOrKInPaper;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   _MaxRadiusOrKInPaper c0       1
//   _MainTex_TexelSize   c1       1
//   _MainTex             s0       1
//

    ps_3_0
    def c2, 0.5, 0, 1, 0
    defi i0, 255, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    mov r0.xy, c2
    mul r0.x, r0.x, c0.x
    mad r0.xz, c1.xyyw, -r0.x, v0.xyyw
    frc r0.w, c0.x
    add r1.x, -r0.w, c0.x
    cmp r0.w, -r0.w, c2.y, c2.z
    cmp r0.y, c0.x, r0.y, r0.w
    add r0.y, r0.y, r1.x
    mov r1.zw, c2.y
    mov r2.xy, c2.y
    mov r3.x, c2.y
    rep i0
      mov r0.w, r0.y
      break_ge r3.x, r0.w
      mov r2.zw, r2.xyxy
      mov r3.y, c2.y
      rep i0
        mov r0.w, r0.y
        break_ge r3.y, r0.w
        mad r1.xy, r3, c1, r0.xzzw
        texldl r4, r1, s0
        dp2add r0.w, r2.zwzw, r2.zwzw, c2.y
        dp2add r0.w, r4, r4, -r0.w
        cmp r2.zw, r0.w, r4.xyxy, r2
        add r3.y, r3.y, c2.z
      endrep
      mov r2.xy, r2.zwzw
      add r3.x, r3.x, c2.z
    endrep
    mov oC0.xy, r2
    mov oC0.zw, c2.xyyz

// approximately 44 instruction slots used (2 texture, 42 arithmetic)
"
}
}
 }


 // Stats for Vertex shader:
 //        d3d9 : 5 math
 // Stats for Fragment shader:
 //        d3d9 : 47 math, 9 texture
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 207056
Program "vp" {
SubProgram "d3d9 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   row_major float4x4 glstate_matrix_mvp;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   glstate_matrix_mvp c0       4
//

    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xy
    dp4 o0.x, c0, v0
    dp4 o0.y, c1, v0
    dp4 o0.z, c2, v0
    dp4 o0.w, c3, v0
    mov o1.xy, v1

// approximately 5 instruction slots used
"
}
}
Program "fp" {
SubProgram "d3d9 " {
// Stats: 47 math, 9 textures
Vector 0 [_MainTex_TexelSize]
SetTexture 0 [_MainTex] 2D 0
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   sampler2D _MainTex;
//   float4 _MainTex_TexelSize;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   _MainTex_TexelSize c0       1
//   _MainTex           s0       1
//

    ps_3_0
    def c1, 1, 0, -1, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    add r0.xy, c0, v0
    texld r0, r0, s0
    dp2add r0.z, r0, r0, c1.y
    mov r1.xyz, c1
    mad r2, c0.xyxy, r1.xyxz, v0.xyxy
    texld r3, r2, s0
    texld r2, r2.zwzw, s0
    dp2add r0.z, r3, r3, -r0.z
    cmp r0.xy, r0.z, r3, r0
    dp2add r0.z, r0, r0, c1.y
    dp2add r0.z, r2, r2, -r0.z
    cmp r0.xy, r0.z, r2, r0
    dp2add r0.z, r0, r0, c1.y
    mad r2, c0.xyxy, r1.yxyz, v0.xyxy
    texld r3, r2, s0
    texld r2, r2.zwzw, s0
    dp2add r0.z, r3, r3, -r0.z
    cmp r0.xy, r0.z, r3, r0
    dp2add r0.z, r0, r0, c1.y
    texld r3, v0, s0
    dp2add r0.z, r3, r3, -r0.z
    cmp r0.xy, r0.z, r3, r0
    dp2add r0.z, r0, r0, c1.y
    dp2add r0.z, r2, r2, -r0.z
    cmp r0.xy, r0.z, r2, r0
    dp2add r0.z, r0, r0, c1.y
    mad r1, c0.xyxy, r1.zxzy, v0.xyxy
    texld r2, r1, s0
    texld r1, r1.zwzw, s0
    dp2add r0.z, r2, r2, -r0.z
    cmp r0.xy, r0.z, r2, r0
    dp2add r0.z, r0, r0, c1.y
    dp2add r0.z, r1, r1, -r0.z
    cmp r0.xy, r0.z, r1, r0
    dp2add r0.z, r0, r0, c1.y
    add r1.xy, -c0, v0
    texld r1, r1, s0
    dp2add r0.z, r1, r1, -r0.z
    cmp oC0.xy, r0.z, r1, r0
    mov oC0.zw, c1.y

// approximately 56 instruction slots used (9 texture, 47 arithmetic)
"
}
}
 }


 // Stats for Vertex shader:
 //        d3d9 : 5 math
 // Stats for Fragment shader:
 //        d3d9 : 77 math, 16 texture, 5 branch
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 280264
Program "vp" {
SubProgram "d3d9 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   row_major float4x4 glstate_matrix_mvp;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   glstate_matrix_mvp c0       4
//

    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xy
    dp4 o0.x, c0, v0
    dp4 o0.y, c1, v0
    dp4 o0.z, c2, v0
    dp4 o0.w, c3, v0
    mov o1.xy, v1

// approximately 5 instruction slots used
"
}
}
Program "fp" {
SubProgram "d3d9 " {
// Stats: 77 math, 16 textures, 5 branches
Float 2 [_Jitter]
Vector 1 [_MainTex_TexelSize]
Float 3 [_SoftZDistance]
Vector 0 [_ZBufferParams]
SetTexture 0 [_MainTex] 2D 0
SetTexture 1 [_CameraDepthTexture] 2D 1
SetTexture 2 [_VelTex] 2D 2
SetTexture 3 [_NeighbourMaxTex] 2D 3
SetTexture 4 [_NoiseTex] 2D 4
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   sampler2D _CameraDepthTexture;
//   float _Jitter;
//   sampler2D _MainTex;
//   float4 _MainTex_TexelSize;
//   sampler2D _NeighbourMaxTex;
//   sampler2D _NoiseTex;
//   float _SoftZDistance;
//   sampler2D _VelTex;
//   float4 _ZBufferParams;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   _ZBufferParams      c0       1
//   _MainTex_TexelSize  c1       1
//   _Jitter             c2       1
//   _SoftZDistance      c3       1
//   _MainTex            s0       1
//   _CameraDepthTexture s1       1
//   _VelTex             s2       1
//   _NeighbourMaxTex    s3       1
//   _NoiseTex           s4       1
//

    ps_3_0
    def c4, -5, 1, -2, 3
    def c5, 1, 0, 11, -2
    def c6, 0.75, 10, 0.0999999642, 0.949999988
    defi i0, 11, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    add r0.x, c5.x, -v0.y
    cmp r0.y, c1.y, v0.y, r0.x
    mul r0.xzw, c5.xyyy, v0.x
    texldl r1, r0.xyww, s3
    mul r2, c5.xxyy, v0.xyxx
    texldl r3, r2, s0
    texldl r0, r0, s2
    texldl r4, r2, s1
    mad r0.z, c0.x, r4.x, c0.y
    rcp r0.z, r0.z
    mul r2, r2, c5.z
    texldl r2, r2, s4
    mad r0.w, r2.x, -c5.w, -c5.x
    mul r2, r3, c6.x
    mov r3.y, c6.y
    add r1.z, r3.y, c2.x
    rcp r1.z, r1.z
    rcp r1.w, c3.x
    dp2add r0.x, r0, r0, c5.y
    rsq r0.x, r0.x
    rcp r0.y, r0.x
    mul r3.x, r0.y, c6.z
    rcp r3.x, r3.x
    mov r4.w, c5.y
    mov r5, r2
    mov r3.y, c6.x
    mov r3.z, c5.y
    rep i0
      add r6.xy, r3.z, c4
      cmp r3.w, -r6_abs.x, c5.y, c5.x
      mad r6.x, r0.w, c2.x, r3.z
      dp2add r6.x, r6.x, r1.z, -c5.x
      mul r6.zw, r1.xyxy, r6.x
      mad r4.xy, r1, r6.x, v0
      add r6.x, -r4.y, c5.x
      cmp r4.z, c1.y, r4.y, r6.x
      texldl r7, r4.xzww, s2
      texldl r8, r4.xyww, s1
      mad r4.z, c0.x, r8.x, c0.y
      rcp r4.z, r4.z
      add r6.x, -r0.z, r4.z
      mad_sat r6.x, r6.x, -r1.w, c5.x
      add r4.z, r0.z, -r4.z
      mad_sat r4.z, r4.z, -r1.w, c5.x
      add r7.zw, -r4.xyxy, v0.xyxy
      dp2add r7.z, r7.zwzw, r7.zwzw, c5.y
      rsq r7.z, r7.z
      rcp r7.z, r7.z
      mad r7.w, r7.z, -r0.x, c5.x
      max r8.x, r7.w, c5.y
      dp2add r6.z, r6.zwzw, r6.zwzw, c5.y
      rsq r6.z, r6.z
      rcp r6.z, r6.z
      dp2add r6.w, r7, r7, c5.y
      rsq r6.w, r6.w
      mad r7.x, r6.z, -r6.w, c5.x
      max r8.y, r7.x, c5.y
      mul r6.x, r6.x, r8.y
      mad r4.z, r4.z, r8.x, r6.x
      rcp r6.x, r6.w
      mul r6.w, r6.x, c6.z
      mad r6.x, r6.x, -c6.w, r6.z
      rcp r6.z, r6.w
      mul_sat r6.x, r6.z, r6.x
      mad r6.z, r6.x, c4.z, c4.w
      mul r6.x, r6.x, r6.x
      mad r6.x, r6.z, -r6.x, c5.x
      mad r6.z, r0.y, -c6.w, r7.z
      mul_sat r6.z, r3.x, r6.z
      mad r6.w, r6.z, c4.z, c4.w
      mul r6.z, r6.z, r6.z
      mad r6.z, r6.w, -r6.z, c5.x
      dp2add r4.z, r6.x, r6.z, r4.z
      texldl r7, r4.xyww, s0
      mul r7, r4.z, r7
      mad r5, r7, r3.w, r5
      mad r3.y, r4.z, r3.w, r3.y
      mov r3.z, r6.y
    endrep
    rcp r0.x, r3.y
    mul oC0, r0.x, r5

// approximately 98 instruction slots used (16 texture, 82 arithmetic)
"
}
}
 }


 // Stats for Vertex shader:
 //        d3d9 : 5 math
 // Stats for Fragment shader:
 //        d3d9 : 10 math, 2 texture, 5 branch
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 367485
Program "vp" {
SubProgram "d3d9 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   row_major float4x4 glstate_matrix_mvp;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   glstate_matrix_mvp c0       4
//

    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xy
    dp4 o0.x, c0, v0
    dp4 o0.y, c1, v0
    dp4 o0.z, c2, v0
    dp4 o0.w, c3, v0
    mov o1.xy, v1

// approximately 5 instruction slots used
"
}
}
Program "fp" {
SubProgram "d3d9 " {
// Stats: 10 math, 2 textures, 5 branches
Vector 0 [_MainTex_TexelSize]
SetTexture 0 [_MainTex] 2D 0
SetTexture 1 [_VelTex] 2D 1
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   sampler2D _MainTex;
//   float4 _MainTex_TexelSize;
//   sampler2D _VelTex;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   _MainTex_TexelSize c0       1
//   _MainTex           s0       1
//   _VelTex            s1       1
//

    ps_3_0
    def c1, 0.100000001, -0.5, 0, 0
    def c2, 1, 0, 0, 0.0909090936
    defi i0, 11, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    add r0.x, c2.x, -v0.y
    cmp r0.y, c0.y, v0.y, r0.x
    mov r0.x, v0.x
    texld r0, r0, s1
    mov r1, c2.z
    mov r0.z, c2.z
    rep i0
      mad r0.w, r0.z, c1.x, c1.y
      mad r2.xy, r0, -r0.w, v0
      texld r2, r2, s0
      add r1, r1, r2
      add r0.z, r0.z, c2.x
    endrep
    mul oC0, r1, c2.w

// approximately 17 instruction slots used (2 texture, 15 arithmetic)
"
}
}
 }


 // Stats for Vertex shader:
 //        d3d9 : 5 math
 // Stats for Fragment shader:
 //        d3d9 : 37 math, 2 texture, 5 branch
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 416503
Program "vp" {
SubProgram "d3d9 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   row_major float4x4 glstate_matrix_mvp;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   glstate_matrix_mvp c0       4
//

    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xy
    dp4 o0.x, c0, v0
    dp4 o0.y, c1, v0
    dp4 o0.z, c2, v0
    dp4 o0.w, c3, v0
    mov o1.xy, v1

// approximately 5 instruction slots used
"
}
}
Program "fp" {
SubProgram "d3d9 " {
// Stats: 37 math, 2 textures, 5 branches
Vector 4 [_BlurDirectionPacked]
Vector 0 [_MainTex_TexelSize]
Float 2 [_MaxVelocity]
Float 3 [_MinVelocity]
Float 1 [_VelocityScale]
SetTexture 0 [_MainTex] 2D 0
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   float4 _BlurDirectionPacked;
//   sampler2D _MainTex;
//   float4 _MainTex_TexelSize;
//   float _MaxVelocity;
//   float _MinVelocity;
//   float _VelocityScale;
//
//
// Registers:
//
//   Name                 Reg   Size
//   -------------------- ----- ----
//   _MainTex_TexelSize   c0       1
//   _VelocityScale       c1       1
//   _MaxVelocity         c2       1
//   _MinVelocity         c3       1
//   _BlurDirectionPacked c4       1
//   _MainTex             s0       1
//

    ps_3_0
    def c5, 2, -1, 1, 0
    def c6, 2.25, 0.25, -2, 3
    def c7, 0.0625, 0, 0.0588235296, 0
    defi i0, 16, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    mad r0.xy, v0, c5.x, c5.y
    rcp r0.z, c0.z
    mul r1.y, r0.z, c0.w
    mov r1.xzw, c5.zyzw
    mul r0.xy, r0, r1
    mul r1, r1.wzzw, c4.xxyy
    add r1.xy, r1.zwzw, r1
    mov r0.z, -r0.x
    mad r0.zw, c4.z, r0.xyyz, r1.xyxy
    mad r0.xy, c4.w, r0, r0.zwzw
    mul r0.xy, r0, c1.x
    dp2add r0.w, r0, r0, c5.w
    rsq r0.w, r0.w
    rcp r0.z, r0.w
    add r1.x, -r0.z, c2.x
    mul r0.w, r0.w, c2.x
    mul r2.xy, r0.w, r0
    mov r2.z, c2.x
    cmp r0.xyz, r1.x, r0, r2
    texld r1, v0, s0
    mov r2.xy, c6
    mul r0.w, r2.x, c3.x
    mad r0.z, c3.x, -r2.y, r0.z
    rcp r0.w, r0.w
    mul_sat r0.z, r0.w, r0.z
    mad r0.w, r0.z, c6.z, c6.w
    mul r0.z, r0.z, r0.z
    mul r0.z, r0.z, r0.w
    mul r0.xy, r0.z, r0
    mul r0.xy, r0, c0
    mul r0.xy, r0, c7.x
    mov r2, r1
    mov r0.z, c5.w
    rep i0
      mad r3.xy, r0.z, r0, v0
      texld r3, r3, s0
      add r2, r2, r3
      add r0.z, r0.z, c5.z
    endrep
    mul oC0, r2, c7.z

// approximately 44 instruction slots used (2 texture, 42 arithmetic)
"
}
}
 }


 // Stats for Vertex shader:
 //        d3d9 : 5 math
 // Stats for Fragment shader:
 //        d3d9 : 93 math, 16 texture, 5 branch
 Pass {
  ZTest Always
  ZWrite Off
  Cull Off
  GpuProgramID 463209
Program "vp" {
SubProgram "d3d9 " {
// Stats: 5 math
Bind "vertex" Vertex
Bind "texcoord" TexCoord0
Matrix 0 [glstate_matrix_mvp]
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   row_major float4x4 glstate_matrix_mvp;
//
//
// Registers:
//
//   Name               Reg   Size
//   ------------------ ----- ----
//   glstate_matrix_mvp c0       4
//

    vs_3_0
    dcl_position v0
    dcl_texcoord v1
    dcl_position o0
    dcl_texcoord o1.xy
    dp4 o0.x, c0, v0
    dp4 o0.y, c1, v0
    dp4 o0.z, c2, v0
    dp4 o0.w, c3, v0
    mov o1.xy, v1

// approximately 5 instruction slots used
"
}
}
Program "fp" {
SubProgram "d3d9 " {
// Stats: 93 math, 16 textures, 5 branches
Float 2 [_Jitter]
Vector 1 [_MainTex_TexelSize]
Float 3 [_MaxVelocity]
Float 4 [_SoftZDistance]
Vector 0 [_ZBufferParams]
SetTexture 0 [_MainTex] 2D 0
SetTexture 1 [_CameraDepthTexture] 2D 1
SetTexture 2 [_VelTex] 2D 2
SetTexture 3 [_NeighbourMaxTex] 2D 3
SetTexture 4 [_NoiseTex] 2D 4
"//
// Generated by Microsoft (R) HLSL Shader Compiler 6.3.9600.16384
//
// Parameters:
//
//   sampler2D _CameraDepthTexture;
//   float _Jitter;
//   sampler2D _MainTex;
//   float4 _MainTex_TexelSize;
//   float _MaxVelocity;
//   sampler2D _NeighbourMaxTex;
//   sampler2D _NoiseTex;
//   float _SoftZDistance;
//   sampler2D _VelTex;
//   float4 _ZBufferParams;
//
//
// Registers:
//
//   Name                Reg   Size
//   ------------------- ----- ----
//   _ZBufferParams      c0       1
//   _MainTex_TexelSize  c1       1
//   _Jitter             c2       1
//   _MaxVelocity        c3       1
//   _SoftZDistance      c4       1
//   _MainTex            s0       1
//   _CameraDepthTexture s1       1
//   _VelTex             s2       1
//   _NeighbourMaxTex    s3       1
//   _NoiseTex           s4       1
//

    ps_3_0
    def c5, 1, 0, 11, -2
    def c6, 0.150000006, 0.0999999642, 0, 0.949999988
    def c7, -0, -1, -2, -3
    def c8, -4, -5, -6, -7
    def c9, -8, -9, -10, -11
    def c10, -0.791558981, -0.597710013, -2, 3
    def c11, -0.326211989, -0.405809999, 0, 0
    def c12, -0.840143979, -0.0735799968, -0.69591397, 0.457136989
    def c13, -0.203345001, 0.620715976, 0.962339997, -0.194983006
    def c14, 0.473434001, -0.480026007, 0.519456029, 0.767022014
    def c15, 0.185461, -0.893123984, 0.507430971, 0.0644249991
    def c16, 0.896420002, 0.412458003, -0.321940005, -0.932614982
    defi i0, 12, 0, 0, 0
    dcl_texcoord v0.xy
    dcl_2d s0
    dcl_2d s1
    dcl_2d s2
    dcl_2d s3
    dcl_2d s4
    add r0.x, c5.x, -v0.y
    cmp r0.y, c1.y, v0.y, r0.x
    mul r0.xzw, c5.xyyy, v0.x
    texldl r1, r0.xyww, s3
    mul r2, c5.xxyy, v0.xyxx
    texldl r3, r2, s0
    texldl r0, r0, s2
    mul r4, r2, c5.z
    texldl r4, r4, s4
    mad r0.zw, r4.xyxy, -c5.w, -c5.x
    texldl r2, r2, s1
    mad r1.z, c0.x, r2.x, c0.y
    rcp r1.z, r1.z
    mov r2.xy, c1
    mul r2.zw, r2.xyxy, c2.x
    mad r0.zw, r0, r2, r1.xyxy
    mul r1.xy, r2, c3.x
    mul r1.xy, r1, c6.x
    max r2.xy, r0_abs.zwzw, r1
    cmp r1.xy, -r0.zwzw, c5.y, c5.x
    cmp r0.zw, r0, -c5.y, -c5.x
    add r0.zw, r0, r1.xyxy
    mul r0.zw, r0, r2.xyxy
    rcp r1.x, c4.x
    dp2add r0.x, r0, r0, c5.y
    rsq r0.x, r0.x
    rcp r0.y, r0.x
    mul r1.y, r0.y, c6.y
    rcp r1.y, r1.y
    mov r2.w, c5.y
    mov r4, r3
    mov r1.w, c5.x
    mov r5.x, c5.y
    rep i0
      add r6, r5.x, c7
      add r7, r5.x, c8
      add r8, r5.x, c9
      cmp r5.yz, -r6_abs.x, c11.xxyw, c11.z
      cmp r5.yz, -r6_abs.y, c12.xxyw, r5
      cmp r5.yz, -r6_abs.z, c12.xzww, r5
      cmp r5.yz, -r6_abs.w, c13.xxyw, r5
      cmp r5.yz, -r7_abs.x, c13.xzww, r5
      cmp r5.yz, -r7_abs.y, c14.xxyw, r5
      cmp r5.yz, -r7_abs.z, c14.xzww, r5
      cmp r5.yz, -r7_abs.w, c15.xxyw, r5
      cmp r5.yz, -r8_abs.x, c15.xzww, r5
      cmp r5.yz, -r8_abs.y, c16.xxyw, r5
      cmp r5.yz, -r8_abs.z, c16.xzww, r5
      cmp r5.yz, -r8_abs.w, c10.xxyw, r5
      mul r6.xy, r0.zwzw, r5.yzzw
      mad r2.xy, r0.zwzw, r5.yzzw, v0
      add r5.y, -r2.y, c5.x
      cmp r2.z, c1.y, r2.y, r5.y
      texldl r7, r2.xzww, s2
      texldl r8, r2.xyww, s1
      mad r2.z, c0.x, r8.x, c0.y
      rcp r2.z, r2.z
      add r5.y, -r1.z, r2.z
      mad_sat r5.y, r5.y, -r1.x, c5.x
      add r2.z, r1.z, -r2.z
      mad_sat r2.z, r2.z, -r1.x, c5.x
      add r5.zw, -r2.xyxy, v0.xyxy
      dp2add r5.z, r5.zwzw, r5.zwzw, c5.y
      rsq r5.z, r5.z
      rcp r5.z, r5.z
      mad r5.w, r5.z, -r0.x, c5.x
      mul r2.z, r2.z, r5.w
      cmp r2.z, r5.w, r2.z, c5.y
      dp2add r5.w, r6, r6, c5.y
      rsq r5.w, r5.w
      rcp r5.w, r5.w
      dp2add r6.x, r7, r7, c5.y
      rsq r6.x, r6.x
      mad r6.y, r5.w, -r6.x, c5.x
      mul r5.y, r5.y, r6.y
      cmp r5.y, r6.y, r5.y, c5.y
      add r2.z, r2.z, r5.y
      rcp r5.y, r6.x
      mul r6.x, r5.y, c6.y
      mad r5.y, r5.y, -c6.w, r5.w
      rcp r5.w, r6.x
      mul_sat r5.y, r5.w, r5.y
      mad r5.w, r5.y, c10.z, c10.w
      mul r5.y, r5.y, r5.y
      mad r5.y, r5.w, -r5.y, c5.x
      mad r5.z, r0.y, -c6.w, r5.z
      mul_sat r5.z, r1.y, r5.z
      mad r5.w, r5.z, c10.z, c10.w
      mul r5.z, r5.z, r5.z
      mad r5.z, r5.w, -r5.z, c5.x
      dp2add r2.z, r5.y, r5.z, r2.z
      texldl r6, r2.xyww, s0
      mad r4, r6, r2.z, r4
      add r1.w, r1.w, r2.z
      add r5.x, r5.x, c5.x
    endrep
    rcp r0.x, r1.w
    mul oC0, r0.x, r4

// approximately 114 instruction slots used (16 texture, 98 arithmetic)
"
}
}
 }
}
Fallback Off
}